/joy_node:
  ros__parameters:
    autorepeat_rate: 100.0 
    coalesce_interval_ms: 1
    deadzone: 0.3
    device_id: 0
    device_name: ''
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    sticky_buttons: false


